
#@server = https://luisangelri-opulent-garbanzo-7g444v44j662p9g6-8080.preview.app.github.dev
@server = https://semana10-ec03.onrender.com

#Categorias

GET {{server}}/categorias
###
POST {{server}}/categorias
Content-Type: application/json

{"nombre": "Percusion"}

###

################ Instrumentos: ################

GET {{server}}/instrumentos
###
POST {{server}}/instrumentos
Content-Type: application/json

{"nombre": "Piano", "categoria": "http://localhost/api/ec3/categorias/2"}
###
GET {{server}}/instrumentos/3/categoria
###
GET {{server}}/instrumentos?sort=nombre,desc

###
