
#@server = https://luisangelri-opulent-garbanzo-7g444v44j662p9g6-8080.preview.app.github.dev
@server = https://sem10-ev-03.onrender.com

#Categorias

GET {{server}}/categorias
###
POST {{server}}/categorias
Content-Type: application/json

{"nombre": "Percusion"}

###

################ Instrumentos: ################

GET {{server}}/instrumentos
###
POST {{server}}/instrumentos
Content-Type: application/json

{"nombre": "Pandereta", "categoria": "http://localhost/api/ec3/categorias/52"}
###
GET {{server}}/instrumentos/1/categoria
###
GET {{server}}/instrumentos?sort=nombre,desc

###
